apiVersion: v1
kind: Service
metadata:
  name: streamer-service
  labels:
    app: streamer
spec:
  type: NodePort
  ports:
  - port: 8000
    name: first
    targetPort: 8000
    nodePort: 30800
  - port: 8001
    name: second
    targetPort: 8001
    nodePort: 30801
  - port: 8002
    targetPort: 8002
    name: third
    nodePort: 30802
  selector:
    app: streamer          
