apiVersion: v1
kind: Pod
metadata:
  name: transcoder-pod
  labels:
    app: transcoder
spec:
  containers:
  - name: transcoder-cont-0
    image: nfvsap/transcoder:latest
    ports:
    - containerPort: 8000
    - containerPort: 8001
    - containerPort: 8002
