apiVersion: v1
kind: Service
metadata:
  name: cache-sensitive-service
  labels:
    app: cache-sensitive
spec:
  type: NodePort
  ports:
  - port: 8000
    name: first
    targetPort: 8000
    nodePort: 31800
  - port: 8001
    name: second
    targetPort: 8001
    nodePort: 31801
  - port: 8002
    targetPort: 8002
    name: third
    nodePort: 31802
  selector:
    app: cache-sensitive          
