apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-dpdk-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_dpdk
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "sriov-dpdk",
  "type": "sriov",
  "trust": "on",
  "link_state": "enable",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.218.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.218.1"
  }
}'

