---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dpdk-deployment-monitor
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    path: /
    interval: "5s"
    scrapeTimeout: "5s"
  namespaceSelector:
    matchNames:
      - dpdk
  selector:
    matchLabels:
      app: dpdk

---
apiVersion: v1
kind: Service
metadata:
  name: dpdk-deployment-svc
  namespace: dpdk
  labels:
    app: dpdk
spec:
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
  selector:
    app: dpdk

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpdk-deployment
  namespace: dpdk
  labels:
    app: dpdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpdk
  template:
    metadata:
      annotations:
        #k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net1
        k8s.v1.cni.cncf.io/networks: default/sriov-dpdk-b2b-net1,default/sriov-dpdk-b2b-net2
      labels:
        app: dpdk
    spec:
      containers:
      - name: telemetry-exporter
        imagePullPolicy: Always
        image: docker.pkg.github.com/nfvri/dpdk-telemetry-exporter/dpdk-telemetry-exporter:0.1
        command: ["dpdkTelemetryExporter"]
        args: ["-vvv"]
        volumeMounts:
           - mountPath: /var/run/dpdk/
             name: dpdkrun-volume
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
          - containerPort: 8000
      - name: dpdk
        imagePullPolicy: Always
        image: docker.pkg.github.com/nfvri/demovnfs/dpdk-ubuntu-testpmd:v20.08
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10; echo 'Sleeping...'; done"]
        securityContext:
#          privileged: true
          capabilities:
            add: ["IPC_LOCK"]
        volumeMounts:
           - mountPath: /hugepages-1Gi
             name: hugepage-1gi
           - mountPath: /var/run/dpdk/
             name: dpdkrun-volume
#          - mountPath: /dev/vfio
#            name: hostvfio-volume
#            readOnly: False
#          - mountPath: /sys/bus/pci/drivers
#            name: hostdrivers-volume
#            readOnly: False
#          - mountPath: /sys/bus/pci/devices
#            name: hostdevices-volume
#            readOnly: False
        resources:
          requests:
            memory: "2Gi"
            cpu: "4000m"
            intel.com/intel_sriov_dpdk_b2b_net1: '1'
            intel.com/intel_sriov_dpdk_b2b_net2: '1'
            hugepages-1Gi: 4Gi
          limits:
            memory: "2Gi"
            cpu: "4000m"
            intel.com/intel_sriov_dpdk_b2b_net1: '1'
            intel.com/intel_sriov_dpdk_b2b_net2: '1'
            hugepages-1Gi: 4Gi
      nodeSelector:
        kubernetes.io/hostname: clx2
      volumes:
        - name: hugepage-1gi
          emptyDir:
            medium: HugePages-1Gi
        - name: dpdkrun-volume
          emptyDir: {}
#        - name: hosthp-volume
#          hostPath:
#            path: /dev/hugepages
#            type: Directory
#        - name: hostvfio-volume
#          hostPath:
#            path: /dev/vfio
#            type: Directory
#        - name: hostdrivers-volume
#          hostPath:
#            path: /sys/bus/pci/drivers
#            type: Directory
#        - name: hostdevices-volume
#          hostPath:
#            path: /sys/bus/pci/devices
#            type: Directory

